Harmony 55/story list view/seulki
itmca/harmony-react-native pull request #20
Opened 2022-04-30 12:05 UTC by SeulKiLeee

## Ticket
https://itmca-harmony.atlassian.net/browse/HARMONY-55

## Description

스토리 리스트 UI 작업 완료. 

## Check Points

1) 피그마의 스토리 리스트 UI 디자인 가이드에서 벗어난 점이 없는지 확인 부탁드립니다.
2) 하단 스크롤 컴포넌트가 잘 작동 되는지 확인 부탁드립니다.
3) 하단으로 스크롤링 했을 경우 TOP 으로 이동하는 플로팅 버튼이 보이고, 버튼을 눌렀을 때 스크롤의 최상단으로 이동하는 이벤트가 잘 적용 되는지 확인 부탁드립니다.

## Checklist:
- [ ] 기존 코드 컨벤션(파일 이름 및 위치, 변수 이름 등)과 부합하는 코드를 작성했습니다.
- [ ] KISS, DRY, YAGNI 원칙을 지켰습니다.
- [ ] 이번 변경으로 인한 사이드이펙트를 충분히 고려하였습니다.
- [ ] Android, iOS 모두 정상 동작하는 것을 확인하였습니다.
- [ ] 이번 변경에 대한 테스트를 추가했습니다.
- [ ] 이번 변경 사항은 문서 변경을 필요로 합니다.
    - [ ] 필요한 문서 업데이트를 완료하였습니다.

## Reviewers:
- [ ] @border-line 
- [ ] @ironprayer

2022-04-30 12:10 UTC, border-line commented on app/components/story-list/ChipItem.tsx
> +const ChipItem = ({item, onPress, backgroundColor, textColor, marginLeft}) => (
Props 선언하지 않고 해도 문제 없나요??

2022-04-30 12:12 UTC, border-line commented on app/components/story-list/ChipList.tsx
> +  {
chipData는 Props로 받게 해야 여러군데서 재활용이 가능할 것 같아요.

2022-04-30 12:23 UTC, border-line requested changes
코멘트 단 것에 추가로 아래 파일명 변경 제안드려 봅니다:)
- StoryListScrollView -> ScrollView
- StoryListTopFixed -> TopFixed

2022-04-30 12:23 UTC, border-line commented on app/pages/StoryList/StoryListScrollView.tsx
> +const StoryViewData: ItemData[] = [
일반 변수명 시작은 소문자로 하는게 일반적인 규칙인 것 같아요.

2022-04-30 12:30 UTC, SeulKiLeee commented on app/pages/StoryList/StoryListScrollView.tsx
> +const StoryViewData: ItemData[] = [
수정 했습니다!

2022-04-30 13:40 UTC, SeulKiLeee commented on app/components/story-list/ChipList.tsx
> +  {
수정 했습니다~!

2022-04-30 13:54 UTC, SeulKiLeee commented on app/components/story-list/ChipItem.tsx
> +const ChipItem = ({item, onPress, backgroundColor, textColor, marginLeft}) => (
네 문제는 없는데 타입 오류가 날 것 같아서 타입 추가해줬는데, 확인 부탁드립니다 :)

2022-05-07 11:58 UTC, border-line approved these changes

2022-05-07 11:59 UTC, merged